# Generated by Django 4.2.7 on 2023-12-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_photo_profile_avatar_profile_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.AddField(
            model_name='profile',
            name='clave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='puesto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
