# Generated by Django 4.2.7 on 2023-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_bio_profile_area_rename_avatar_profile_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clave',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='puesto',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
