# Generated by Django 4.2.7 on 2023-12-05 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_area_alter_profile_clave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='foto',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='puesto',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=191011022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
